[package]
name = "skywalker"
version = "1.0.1"
edition = "2018"

[dependencies]
pancurses = { version = "^0.16.1", features = ["win32"] }
thiserror = "^1.0.24"
anyhow = "^1.0.40"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

